export enum MovieType {
  Action = 'action',
  Adventure = 'adventure',
  Animation = 'animation',
  Biography = 'biography',
  Comedy = 'comedy',
  Crime = 'crime',
  Documentary = 'documentary',
  Drama = 'drama',
  Family = 'family',
  Fantasy = 'fantasy',
  History = 'history',
  Horror = 'horror',
  Music = 'music',
  Musical = 'musical',
  Mystery = 'mystery',
  Romance = 'romance',
  SciFi = 'sci-fi',
  Sport = 'sport',
  Thriller = 'thriller',
  War = 'war',
  Western = 'western'
}